from selenium import webdriver
driver=webdriver.Firefox(executable_path="/home/sumit/ss/geckodriver")
driver.get('https://www.facebook.com/')
driver.maximize_window()
print('Title:',driver.title)
print('Current URL:',driver.current_url)
driver.get('https://github.com/SumitVashist')
print('Title:',driver.title)
print('Current URL:',driver.current_url)
driver.back()
print('After Back current url:',driver.current_url)
driver.forward()
print('After Forward current url:',driver.current_url)
driver.close() 